name: Deploy news.json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */3 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload news.json to Timeweb
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TIMEWEB_HOST }}
          username: ${{ secrets.TIMEWEB_USER }}
          password: ${{ secrets.TIMEWEB_PASSWORD }}
          port: ${{ secrets.TIMEWEB_PORT }}
          source: "news.json"
          target: "/home/cp522538/news/public_html/"
